# Generated by Django 5.0.6 on 2024-07-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
